FROM oven/bun:1.3.11

WORKDIR /app

COPY . .
RUN bun install --frozen-lockfile
RUN bun run build --filter=@repo/contracts

WORKDIR /app/clients/web

EXPOSE 3000

CMD ["bun", "run", "dev", "--", "--hostname", "0.0.0.0"]
